wpa_supplicant_networks:
    - ssid: ENC[AES256_GCM,data:+JJb7anJIASxdgxtXHs9jS6vnbILwGWV,iv:gZitND1X3JgMPUZsvpvQcCKLGcmcYVY99TnKjx/R7HA=,tag:EbILury5aMJO/+t9izEFog==,type:str]
      psk: ENC[AES256_GCM,data:fUic/WSM91e6LRFmmXUK0fo7+lM=,iv:aRRQ5nlV6pqf77w1GjuNMjjDkBUsCqgh33Ppj9zPlm4=,tag:AWSjIth9SWwLjJcWvY7z+w==,type:str]
    - ssid: ENC[AES256_GCM,data:EqbC2cWvFI4CoXpxgMy5wWrGlpc7,iv:miZyU2RLlIz6cV0zFNmz1jtbSu9SLnvW94FXLqzOfcA=,tag:9/6qkCARdRCmWgZQSnedbg==,type:str]
      psk: ENC[AES256_GCM,data:vz1ziOtDT4GtTcJ0,iv:wvf4fwwTiYf2B0uSCrA/R46W7iyZOf5c4SAbDbwBSLg=,tag:EtAKh5LxkhV/mLm06WsMrQ==,type:str]
    - ssid: ENC[AES256_GCM,data:cvCaiQpJ1VCrv+xVMNK/YOYT,iv:3cjhsNKRUbLX5mOkfntRgfDAV9C9tdQicxc2ZFBNND4=,tag:K0feVFhiYm19BFxKVOa3nw==,type:str]
      psk: ENC[AES256_GCM,data:3HC1xGjKdmSX,iv:W0Skw4KlXDA5zSrNIG9jhQvqwpYzt2N+VtUu8O6YTxw=,tag:1jVgM/w2c3ERzL0RXREe/w==,type:str]
    - ssid: ENC[AES256_GCM,data:CY4ZXcmRcxSd5Q==,iv:2ltHIBe8JOcqrWg9UyhEa/aJQuF5GzpQT75D5tV6RyY=,tag:IKY1Yarq4acE4tXWcFhbyw==,type:str]
      psk: ENC[AES256_GCM,data:0xJr2JeZNRE=,iv:Y5nSZmyU5VP14btjdn8f74pi6GSALmfzCWLrrcz48rQ=,tag:1mlSR6ikZhgaryOuUkikSQ==,type:str]
      #ENC[AES256_GCM,data:r3dvZLfVP0DFYPAqPY/biyFkf73BSj0QFhYw2ZYWHrftuVa1oQE3dQ+18pebtqVsc6jyuP/K8zSun3ZMJRaaCpVh0g33,iv:pBP0Ut6ippqaDJKjHWPQLi2QY/nl5c5DJbl35jjWOzk=,tag:X8wViKzzub+/M6lDdwUf1A==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c4vsjy9rqqtxlju2k8dg4agehr4cr887wc9fa6ycjgsvslu7gvmq2kw5ad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUmdFODFVL0p1MlhnZ0wz
            b2xrM2ZrNGFNUk9zYlFCUERMNTVTaVkyUHhFCkdpeEFrbG84bnk4N3pIT0J3alVs
            K29yOFUzcm91R0tnWXBBdWZhOGpxMXcKLS0tIExaRDArWXpMRXRTSldFY2FmaDhW
            eUhjS3JLTGpidzB1TTUzenRoSFBWeGcK/cQoKYD0ekPkxwM/TMfHWJOpLksG75zI
            GpyQ1d83m/ApDBgPwBLXCZGlarYAEiyinA1z00/FhA/AQPo2FgpVjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T17:14:56Z"
    mac: ENC[AES256_GCM,data:ch6tDfD7z0dFmGKx6BR6MKLedz2H4S+ZeYDOu0uzUJolDJc8Z6PYdX16VfH7Yvwa20Wezm9vLIsmJa+aejHYC89cYhEZnYxfd4O7XtzinZT9rsHktb5315LzbaiyDOf29nFduxqAEh9Ig3jX0JybqxPluWfi4tdm5WJWBKGutTk=,iv:zn0lTTWlUeED/6RK1oAKmal2mY2ImHQcwlBqS/QeL/g=,tag:lltp8BBSZuXfY5aGVqcwNA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
