---
camera:
  delay: 1
  output_directory: /home/corentin/photos/captures
  count: template
processing:
  preset: RegularDoubleStripWithTitle
  title:
    image_path: /home/corentin/photobooth/titles/alo&coco.png
  output_directory: /home/corentin/photos/processed
presets: {}
printing:
  copies: 1
  enabled: true
  delay: 1
  destination: DS620_6x2_2_dnpwcm
  # destination: DS620_4x6_dnpwcm
