---
camera:
  delay: 0
  output_directory: /tmp/photobooth/captures
processing:
  background:
    color: "white"
  captures:
    filters:
      - name: LevelImage
        params:
          black: 0
          white: 20
    margin: 2
  title:
    image_path: null
    filters:
      - name: Inverted
  output_directory: /tmp/photobooth/processed
gpio:
  led: 27
  button: 17
