---
presets:
  RegularStripWithTitle:
    template:
      name: StripWithTitle
      params:
        background_color: white
        margin: 5%
    filters: []
    title_filters:
      - name: Inverted
  RegularDoubleStripWithTitle:
    template:
      name: DoubleStripWithTitle
      params:
        background_color: white
        margin: 10%
    # filters:
    #   - name: ColorLevel
    #     params:
    #       red: [0, 200]
    #       green: [0, 220]
    #       blue: [0, 200]
    # title_filters:
    #   - name: Inverted
  BlackAndWhiteStripWithTitle:
    template:
      name: StripWithTitle
      params:
        background_color: black
        margin: 5%
    filters:
      - name: BlackAndWhite
  BlackAndWhiteDoubleStripWithTitle:
    template:
      name: DoubleStripWithTitle
      params:
        background_color: black
        margin: 5%
    filters:
      - name: BlackAndWhite
